sonar.projectKey=securetrack-devsecops
sonar.organization=your-org
sonar.projectName=SecureTrack DevSecOps

sonar.sources=app/backend/src,app/frontend/src
sonar.tests=app/backend/tests,app/frontend/tests
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/reports/**

sonar.javascript.lcov.reportPaths=app/backend/coverage/lcov.info

sonar.qualitygate.wait=true
